PERMISSIONS: dict[str, str] = {
    "dashboard.read": "Consulter le tableau de bord",
    "platform.read": "Consulter les plateformes",
    "platform.create": "Créer des plateformes",
    "platform.update": "Modifier les plateformes",
    "platform.archive": "Supprimer les plateformes",
    "platform.scan": "Lancer des scans de plateforme",
    "service.read": "Consulter les services",
    "service.create": "Créer des services",
    "service.update": "Modifier les services",
    "service.archive": "Supprimer les services",
    "service.import": "Importer des services",
    "service.scan": "Vérifier des services",
    "notification.read": "Consulter les notifications",
    "notification.hide": "Masquer les notifications",
    "history.read": "Consulter l’historique",
    "history.hide": "Masquer l’historique",
    "settings.read": "Consulter les paramètres",
    "settings.update": "Modifier les paramètres",
    "user.read": "Consulter les utilisateurs",
    "user.manage": "Gérer les utilisateurs",
    "permission.manage": "Gérer les autorisations",
}
